matrix:
  include:
    - language: go
      go:
        - 1.13.x
      before_install:
        - cd golang-bench/
      script:
        - go test .

    - language: java
      jdk: openjdk8
      before_install:
        - cd java-netty/
      script: mvn test